id: PDB7C21C7
initial_creation_type: input
source_metadata:
  Title: Vādanyāyaṭīkā
  Editor: Sāṅkṛtyāyana, Rāhula
  Publisher: Central Institute of Higher Tibetan Studies,
  Place of Publication: Sarnath
  Year: '2007'
  Vādanyāyaṭīkā:
    Text Version: Romanized
    Input Personnel: Milan Shakya
    Input Date: '2013'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of the Exact Methods
    Sponsor: ''
created_at: '2022-03-08T16:47:22.302428'
last_modified_at: '2022-03-08T16:47:22.302436'
